//! Encrypted page captures, one file per capture, beside the store file.
//!
//! # Why captures are files and not a field in the store
//!
//! The store is ONE encrypted JSON document that is fully re-serialized,
//! re-encrypted and rewritten on EVERY mutation (see `Store::save`). A
//! multi-megabyte picture in that document would be rewritten every time a
//! bookmark is added. So pictures live in their own files and the store
//! keeps only metadata. That split is the whole reason this module exists.
//!
//! It is the file-lifecycle and encryption layer only: no serde model, no
//! search, no IPC, no UI.
//!
//! # File format
//!
//! `MAGIC(8) || version(1) || nonce(24) || ciphertext||tag`, and the WHOLE
//! header is the AEAD's additional data, so altering the version or the
//! nonce fails authentication instead of being quietly accepted. This is the
//! same discipline `format.rs` applies to the store's own header.
//!
//! # Why the temporary file has a random name
//!
//! A temporary file named after its target is predictable, and here the name
//! would be derived from a caller-supplied id in a directory that exists for
//! the lifetime of the profile. Two weaknesses follow from a predictable temp
//! name:
//!
//! * a pre-existing symlink at that path is FOLLOWED by an ordinary create,
//!   so a write lands wherever the link points, and
//! * two writers for the same id share one temporary inode, so one can be
//!   renamed into place while the other still holds it open and keeps
//!   writing through the descriptor, corrupting a file whose `put` already
//!   returned an error.
//!
//! Both disappear with a random temp name plus `create_new`, which refuses
//! to open anything that already exists, symlink included. Found in review
//! of the first draft of this module. The store's own writer named its temp
//! file after the Library until 2026-09-27 and now works the same way.

use std::collections::BTreeSet;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use zeroize::Zeroizing;

use crate::crypto::{self, KEY_LEN, NONCE_LEN};
use crate::error::StoreError;

const MAGIC: &[u8; 8] = b"RBBLOB\x00\x01";
const BLOB_VERSION: u8 = 1;
const HEADER_LEN: usize = MAGIC.len() + 1 + NONCE_LEN;

/// Domain separator for the blob subkey. The store already applies this
/// trick to its passphrase pre-hash: keys for different jobs must be
/// different bytes, so that a weakness in one use cannot be carried into
/// the other by reusing the material.
const BLOB_KEY_DOMAIN: &[u8] = b"patanyx-store-blob-v1";

/// Longest accepted id. Ids are generated by the store (32 hex characters);
/// this bound exists so a caller bug cannot produce a filename the platform
/// refuses for length.
const MAX_ID_LEN: usize = 64;

/// Names Windows treats as devices rather than files, whatever the
/// extension and whatever the case. Rejected even though the store's own
/// ids can never collide with one: `validate_id` is a public contract, and
/// a contract that holds only for today's caller is not a contract.
const RESERVED_STEMS: [&str; 22] = [
    "con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7", "com8",
    "com9", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9",
];

/// An id is about to become a FILENAME, so it is checked against a positive
/// allowlist before anything touches the filesystem.
///
/// Lowercase only. Windows filesystems are usually case-insensitive, so
/// accepting both cases would let `ab` and `AB` name one file on one
/// platform and two on another, which would make `prune` delete a blob the
/// caller listed under the other spelling.
///
/// A rejected id is `NotFound`, never an io error: a caller bug and a disk
/// problem must stay distinguishable.
fn validate_id(id: &str) -> Result<(), StoreError> {
    let ok = !id.is_empty()
        && id.len() <= MAX_ID_LEN
        && id
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_' || b == b'-');
    if !ok || RESERVED_STEMS.contains(&id) {
        return Err(StoreError::NotFound(format!("unusable blob id: {id:?}")));
    }
    Ok(())
}

/// `SHA-256(domain || 0x00 || store_key)`, so the blob key and the store key
/// are never the same bytes.
fn derive_blob_key(store_key: &[u8; KEY_LEN]) -> Zeroizing<[u8; KEY_LEN]> {
    let mut hasher = Sha256::new();
    hasher.update(BLOB_KEY_DOMAIN);
    hasher.update([0x00]);
    hasher.update(store_key);
    let digest = hasher.finalize();
    let mut key = Zeroizing::new([0u8; KEY_LEN]);
    key.copy_from_slice(&digest);
    key
}

/// An UNPREDICTABLE temporary filename, which is half of why a write here
/// cannot be diverted. The other half is `create_new`, which refuses to open
/// anything already present. A name derived from the target (the shape the
/// store's own writer used until 2026-09-27) can be pre-created as a symlink
/// by anyone who can write to the directory, and an ordinary create follows
/// it.
fn temp_name() -> String {
    let suffix: [u8; 16] = crypto::random_bytes();
    let mut name = String::from(".tmp-");
    for b in suffix {
        name.push_str(&format!("{b:02x}"));
    }
    name
}

pub struct BlobStore {
    dir: PathBuf,
    key: Zeroizing<[u8; KEY_LEN]>,
}

impl BlobStore {
    /// Opens (creating if absent) the directory that holds the blobs.
    ///
    /// On unix a created directory is made 0700 BY `DirBuilder`, not chmodded
    /// afterwards: a create-then-chmod leaves a window in which the umask
    /// decides who can read it. An EXISTING directory is left exactly as it
    /// is, since silently tightening a directory the caller chose could break
    /// something else that legitimately shares it.
    pub fn open(dir: &Path, store_key: &[u8; KEY_LEN]) -> Result<Self, StoreError> {
        if !dir.exists() {
            let mut builder = fs::DirBuilder::new();
            builder.recursive(true);
            #[cfg(unix)]
            {
                use std::os::unix::fs::DirBuilderExt;
                builder.mode(0o700);
            }
            builder.create(dir)?;
        }
        Ok(Self {
            dir: dir.to_path_buf(),
            key: derive_blob_key(store_key),
        })
    }

    fn path_for(&self, id: &str) -> PathBuf {
        self.dir.join(id)
    }

    /// Encrypts and writes, replacing any previous blob for `id`. Returns
    /// the number of bytes on disk.
    pub fn put(&self, id: &str, plaintext: &[u8]) -> Result<u64, StoreError> {
        validate_id(id)?;
        let nonce: [u8; NONCE_LEN] = crypto::random_bytes();
        let mut header = Vec::with_capacity(HEADER_LEN);
        header.extend_from_slice(MAGIC);
        header.push(BLOB_VERSION);
        header.extend_from_slice(&nonce);
        let ciphertext = crypto::encrypt(&self.key, &nonce, &header, plaintext)?;

        let mut bytes = Vec::with_capacity(header.len() + ciphertext.len());
        bytes.extend_from_slice(&header);
        bytes.extend_from_slice(&ciphertext);
        let written = bytes.len() as u64;
        self.write_atomically(&self.path_for(id), &bytes)?;
        Ok(written)
    }

    /// Write to a UNIQUE temp file, fsync, rename over the target.
    ///
    /// The temp name carries 16 random bytes and is opened with
    /// `create_new`, so an existing file or symlink at that path is a
    /// failure rather than something to write through. See the module docs
    /// for the two weaknesses this closes.
    fn write_atomically(&self, path: &Path, bytes: &[u8]) -> Result<(), StoreError> {
        let tmp = self.dir.join(temp_name());

        let mut options = fs::OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        {
            // 0600 must hold BEFORE any ciphertext reaches disk.
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&tmp)?;
        let result = file
            .write_all(bytes)
            .and_then(|()| file.sync_all())
            .map_err(StoreError::Io);
        drop(file);
        if let Err(e) = result {
            let _ = fs::remove_file(&tmp);
            return Err(e);
        }
        if let Err(e) = fs::rename(&tmp, path) {
            let _ = fs::remove_file(&tmp);
            return Err(StoreError::Io(e));
        }
        Ok(())
    }

    /// Decrypts one blob. A wrong key and a tampered file are the same
    /// `AuthFailed`, exactly as the store treats a wrong passphrase.
    pub fn get(&self, id: &str) -> Result<Zeroizing<Vec<u8>>, StoreError> {
        validate_id(id)?;
        let raw = fs::read(self.path_for(id))?;
        if raw.len() < HEADER_LEN || &raw[..MAGIC.len()] != MAGIC {
            return Err(StoreError::BadFormat("not a blob file".to_string()));
        }
        let version = raw[MAGIC.len()];
        if version != BLOB_VERSION {
            return Err(StoreError::BadFormat(format!(
                "unsupported blob version {version}"
            )));
        }
        let mut nonce = [0u8; NONCE_LEN];
        nonce.copy_from_slice(&raw[MAGIC.len() + 1..HEADER_LEN]);
        crypto::decrypt(&self.key, &nonce, &raw[..HEADER_LEN], &raw[HEADER_LEN..])
    }

    /// Removes a blob. An absent blob is success: the caller's goal is that
    /// it not be there.
    pub fn delete(&self, id: &str) -> Result<(), StoreError> {
        validate_id(id)?;
        match fs::remove_file(self.path_for(id)) {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(StoreError::Io(e)),
        }
    }

    pub fn exists(&self, id: &str) -> bool {
        validate_id(id).is_ok() && self.path_for(id).is_file()
    }

    /// Every blob id on disk. Temp files and anything that is not a regular
    /// file are skipped, so a half-written blob is never reported as one.
    pub fn ids(&self) -> Result<Vec<String>, StoreError> {
        let mut out = Vec::new();
        for entry in fs::read_dir(&self.dir)? {
            let entry = entry?;
            if !entry.file_type()?.is_file() {
                continue;
            }
            let Some(name) = entry.file_name().to_str().map(str::to_string) else {
                continue;
            };
            if validate_id(&name).is_ok() {
                out.push(name);
            }
        }
        out.sort();
        Ok(out)
    }

    pub fn total_bytes(&self) -> Result<u64, StoreError> {
        let mut total = 0u64;
        for id in self.ids()? {
            total = total.saturating_add(fs::metadata(self.path_for(&id))?.len());
        }
        Ok(total)
    }

    /// Deletes every blob whose id is not in `keep`, returning how many went.
    ///
    /// EVERY id in `keep` is validated first, and an unusable one aborts
    /// before a single file is touched. Silently ignoring it would mean
    /// treating a blob the caller asked to keep as one to delete, which is
    /// the one mistake here that cannot be undone.
    pub fn prune(&self, keep: &[String]) -> Result<usize, StoreError> {
        let mut wanted = BTreeSet::new();
        for id in keep {
            validate_id(id)?;
            wanted.insert(id.as_str());
        }
        let mut removed = 0usize;
        for id in self.ids()? {
            if !wanted.contains(id.as_str()) {
                fs::remove_file(self.path_for(&id))?;
                removed += 1;
            }
        }
        Ok(removed)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        let unique: [u8; 8] = crypto::random_bytes();
        let mut name = format!("patanyx-blob-test-{tag}-");
        for b in unique {
            name.push_str(&format!("{b:02x}"));
        }
        std::env::temp_dir().join(name)
    }

    fn store(dir: &Path) -> BlobStore {
        BlobStore::open(dir, &[7u8; KEY_LEN]).expect("open")
    }

    #[test]
    fn a_capture_survives_the_encrypted_round_trip() {
        let dir = scratch("roundtrip");
        let blobs = store(&dir);
        let png = b"\x89PNG\r\n\x1a\n and then some bytes";
        let written = blobs.put("cap0001", png).expect("put");
        assert!(written > png.len() as u64, "header and tag add bytes");
        assert_eq!(&blobs.get("cap0001").expect("get")[..], png);
        // The bytes on disk are NOT the plaintext.
        let raw = fs::read(dir.join("cap0001")).expect("read");
        assert!(!raw.windows(4).any(|w| w == b"PNG "), "plaintext on disk");
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn a_wrong_key_fails_as_authentication_not_as_a_decode_error() {
        let dir = scratch("wrongkey");
        store(&dir).put("cap0001", b"secret").expect("put");
        let other = BlobStore::open(&dir, &[9u8; KEY_LEN]).expect("open");
        assert!(matches!(other.get("cap0001"), Err(StoreError::AuthFailed)));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn flipping_any_header_byte_breaks_authentication() {
        // Proves the WHOLE header is the AAD rather than just part of it:
        // every byte of magic, version and nonce is flipped in turn.
        let dir = scratch("aad");
        let blobs = store(&dir);
        blobs.put("cap0001", b"secret bytes").expect("put");
        let good = fs::read(dir.join("cap0001")).expect("read");
        for index in 0..HEADER_LEN {
            let mut bad = good.clone();
            bad[index] ^= 0xFF;
            fs::write(dir.join("cap0001"), &bad).expect("write");
            let verdict = blobs.get("cap0001");
            assert!(
                verdict.is_err(),
                "byte {index} of the header was not authenticated"
            );
        }
        // And the ciphertext itself.
        let mut bad = good.clone();
        let last = bad.len() - 1;
        bad[last] ^= 0xFF;
        fs::write(dir.join("cap0001"), &bad).expect("write");
        assert!(matches!(blobs.get("cap0001"), Err(StoreError::AuthFailed)));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn an_id_that_could_escape_the_directory_is_refused_before_any_io() {
        let dir = scratch("ids");
        let blobs = store(&dir);
        let bad = [
            "..",
            "../escape",
            "a/b",
            "a\\b",
            "",
            ".",
            "with space",
            "UPPER",
            "MiXeD",
            "con",
            "nul",
            "com1",
            "tab\there",
        ];
        for id in bad {
            assert!(blobs.put(id, b"x").is_err(), "put accepted {id:?}");
            assert!(blobs.get(id).is_err(), "get accepted {id:?}");
            assert!(blobs.delete(id).is_err(), "delete accepted {id:?}");
            assert!(!blobs.exists(id), "exists accepted {id:?}");
        }
        let long = "a".repeat(MAX_ID_LEN + 1);
        assert!(blobs.put(&long, b"x").is_err(), "length cap not enforced");
        // Nothing was created by any of that.
        assert_eq!(blobs.ids().expect("ids"), Vec::<String>::new());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn delete_is_idempotent_and_exists_tracks_it() {
        let dir = scratch("delete");
        let blobs = store(&dir);
        assert!(!blobs.exists("cap0001"));
        blobs.put("cap0001", b"x").expect("put");
        assert!(blobs.exists("cap0001"));
        blobs.delete("cap0001").expect("delete");
        assert!(!blobs.exists("cap0001"));
        blobs.delete("cap0001").expect("deleting an absent blob is fine");
        assert!(blobs.get("cap0001").is_err());
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn prune_removes_exactly_what_was_not_kept() {
        let dir = scratch("prune");
        let blobs = store(&dir);
        for id in ["cap0001", "cap0002", "cap0003"] {
            blobs.put(id, b"x").expect("put");
        }
        let removed = blobs
            .prune(&["cap0002".to_string()])
            .expect("prune");
        assert_eq!(removed, 2);
        assert_eq!(blobs.ids().expect("ids"), vec!["cap0002".to_string()]);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn prune_refuses_an_unusable_keep_id_before_deleting_anything() {
        // The irreversible case: a malformed id in `keep` must not be
        // quietly dropped, or the blob the caller meant to keep is the one
        // that gets deleted.
        let dir = scratch("prunebad");
        let blobs = store(&dir);
        blobs.put("cap0001", b"x").expect("put");
        assert!(blobs.prune(&["../cap0001".to_string()]).is_err());
        assert!(blobs.exists("cap0001"), "a refused prune deleted a blob");
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn totals_and_ids_ignore_temp_files_and_strangers() {
        let dir = scratch("ids2");
        let blobs = store(&dir);
        blobs.put("cap0001", b"hello").expect("put");
        let real = blobs.total_bytes().expect("total");
        assert!(real > 0);
        // A leftover temp file from an interrupted write, and a stranger
        // whose name is not a usable id, are both invisible here.
        fs::write(dir.join(".tmp-deadbeef"), b"junk").expect("write");
        fs::write(dir.join("NOT-AN-ID"), b"junk").expect("write");
        assert_eq!(blobs.ids().expect("ids"), vec!["cap0001".to_string()]);
        assert_eq!(blobs.total_bytes().expect("total"), real);
        // And a later put still works with that debris present.
        blobs.put("cap0002", b"more").expect("put after debris");
        assert_eq!(blobs.get("cap0002").expect("get").len(), 4);
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn the_blob_key_is_not_the_store_key() {
        let store_key = [42u8; KEY_LEN];
        assert_ne!(&derive_blob_key(&store_key)[..], &store_key[..]);
    }

    #[test]
    fn the_temp_name_is_unpredictable_so_it_cannot_be_pre_created() {
        // The mechanism that closes the diverted-write hole. A name derived
        // from the target can be pre-created as a symlink and followed; a
        // random one cannot be guessed, and `create_new` refuses anything
        // that exists anyway. This pins the first half.
        //
        // NOTE ON WHY THIS TEST EXISTS IN THIS FORM: the obvious test, a
        // symlink planted at the temp path, cannot be written once the path
        // is unguessable. Its first draft planted the symlink at the TARGET
        // instead and passed against the vulnerable implementation as well
        // as the fixed one, which made it worthless. Proving randomness plus
        // reading `create_new` at the call site is the honest substitute.
        let mut seen = BTreeSet::new();
        for _ in 0..64 {
            let name = temp_name();
            assert!(name.starts_with(".tmp-"), "temp files must be recognisable");
            assert!(validate_id(&name).is_err(), "a temp name is never a valid id");
            assert!(seen.insert(name), "temp name repeated");
        }
    }

    #[cfg(unix)]
    #[test]
    fn a_symlink_at_the_target_is_replaced_rather_than_written_through() {
        use std::os::unix::fs::symlink;
        let dir = scratch("symlink");
        let blobs = store(&dir);
        let outside = scratch("symlink-outside");
        fs::create_dir_all(&outside).expect("outside dir");
        let victim = outside.join("victim");
        fs::write(&victim, b"do not touch").expect("victim");
        // The blob path itself is a symlink pointing out of the directory.
        symlink(&victim, dir.join("cap0001")).expect("symlink");
        blobs.put("cap0001", b"new bytes").expect("put replaces the link");
        assert_eq!(
            fs::read(&victim).expect("victim still there"),
            b"do not touch",
            "the write followed a symlink out of the blob directory"
        );
        fs::remove_dir_all(&dir).ok();
        fs::remove_dir_all(&outside).ok();
    }
}
